    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      
      # ဒီ Command ၁ ခုတည်း run လိုက်ရင် 
      # သင့်ရဲ့ app_icon.png (1024x1024) ကို ဖတ်ပြီး 
      # mipmap folder ၅ ခုစလုံးအတွက် လိုအပ်တဲ့ Resolution တွေနဲ့ 
      # ic_launcher.png ဖိုင်အစစ်တွေကို အလိုအလျောက် ဖန်တီးပေးသွားပါလိမ့်မယ်။
      - name: Generate launcher icons
        script: |
          dart run flutter_launcher_icons
      
      - name: Build APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
